DROP TABLE users IF EXISTS;

CREATE TABLE users(
id INT AUTO_INCREMENT  PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR (30) NOT NULL,
email VARCHAR(60) DEFAULT NULL
);

DROP TABLE teachers IF EXISTS;

CREATE TABLE teachers(
id INT AUTO_INCREMENT  PRIMARY KEY,
subject VARCHAR(30) NOT NULL,
grade VARCHAR (30) NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR (30) NOT NULL,
email VARCHAR(60) DEFAULT NULL
);





